version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diriyah-brain-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./chroma_data:/app/chroma_db
    depends_on:
      - redis
      - chroma

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: diriyah-brain-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  redis:
    image: redis:7-alpine
    container_name: diriyah-brain-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: diriyah-brain-chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma

volumes:
  redis_data:
  chroma_data:
