services:
  - type: web
    name: diriyah-brain-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///diriyah.db
      - key: TEAMS_API_KEY
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: ACONEX_API_KEY
        sync: false
      - key: P6_API_KEY
        sync: false
      - key: POWERBI_API_KEY
        sync: false
      - key: YOLO_MODEL_PATH
        value: yolov8n.pt
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://diriyah-ai-demo.onrender.com/drive/callback

