services:
  - type: web
    name: diriyah-brain-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false

  - type: web
    name: diriyah-brain-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    autoDeploy: true

databases:
  - name: diriyah-brain-redis
    plan: starter
    ipAllowList: [] # open access (configure for prod)
